name: "Code Checks"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze Code Quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup properties
      env:
        GRADLE_PROPERTIES: ${{ secrets.CURSE_FORGE_API}}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        echo "GRADLE_USER_HOME=${HOME/.gradle}" >> $GITHUB_ENV
        echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
        chmod +rwx gradlew
    #- name: Build Mod
    #  run: ./gradlew build

    - name: Minecraft Forge client startup test
      # You may pin to the exact commit or the version.
      # uses: Charismara/forge-client-startup-action@f46a35c65d1c7abf8d0f248a2765116a6db9f6b9
      uses: Charismara/forge-client-startup-action@0.9
      with:
        # Url to clone the current repository
        githubCloneUrl: https://github.com/Other-Living-Beings/other-living-beings.git
